export const LOCATIONS = [
  { id: "1", name: "Raja Ampat", country: "Indonesia", diveCount: 312, image: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=800&q=80" },
  { id: "2", name: "Great Barrier Reef", country: "Australia", diveCount: 489, image: "https://images.unsplash.com/photo-1583212292454-27b36f3a7414?auto=format&fit=crop&w=800&q=80" },
  { id: "3", name: "Palau", country: "Micronesia", diveCount: 201, image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80" },
  { id: "4", name: "Maldives", country: "Maldives", diveCount: 376, image: "https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&w=800&q=80" },
  { id: "5", name: "Galápagos", country: "Ecuador", diveCount: 143, image: "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80" },
  { id: "6", name: "Komodo", country: "Indonesia", diveCount: 228, image: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=800&q=80" },
  { id: "7", name: "Cocos Island", country: "Costa Rica", diveCount: 97, image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80" },
  { id: "8", name: "Bali", country: "Indonesia", diveCount: 541, image: "https://images.unsplash.com/photo-1559591935-c79d543e5e5d?auto=format&fit=crop&w=800&q=80" },
  { id: "9", name: "Cozumel", country: "Mexico", diveCount: 302, image: "https://images.unsplash.com/photo-1487149996460-b25b91a90d19?auto=format&fit=crop&w=800&q=80" },
  { id: "10", name: "Red Sea", country: "Egypt", diveCount: 417, image: "https://images.unsplash.com/photo-1559825481-12a05cc00344?auto=format&fit=crop&w=800&q=80" },
];

export const CREATURES = [
  { id: "1", name: "Manta Ray", tagline: "Graceful giants of the open ocean", image: "https://images.unsplash.com/photo-1564146527183-d04e6a6eb56a?auto=format&fit=crop&w=800&q=80" },
  { id: "2", name: "Whale Shark", tagline: "The ocean's gentle giant", image: "https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=800&q=80" },
  { id: "3", name: "Sea Turtle", tagline: "Ancient mariners of the deep", image: "https://images.unsplash.com/photo-1508193638397-1cc4ff24c8a7?auto=format&fit=crop&w=800&q=80" },
  { id: "4", name: "Hammerhead Shark", tagline: "Masters of the reef wall", image: "https://images.unsplash.com/photo-1491438590914-bc09024cb91d?auto=format&fit=crop&w=800&q=80" },
  { id: "5", name: "Nudibranch", tagline: "Tiny jewels of the sea floor", image: "https://images.unsplash.com/photo-1565128939010-4d26d6b7e6f5?auto=format&fit=crop&w=800&q=80" },
  { id: "6", name: "Pygmy Seahorse", tagline: "Masters of camouflage", image: "https://images.unsplash.com/photo-1583212292454-27b36f3a7414?auto=format&fit=crop&w=800&q=80" },
  { id: "7", name: "Thresher Shark", tagline: "Dawn hunters of Malapascua", image: "https://images.unsplash.com/photo-1517699418-26f4f8d1ed49?auto=format&fit=crop&w=800&q=80" },
  { id: "8", name: "Dugong", tagline: "Sea cows of the shallows", image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80" },
];

export const DIVE_CENTERS = [
  {
    id: "1",
    name: "Blue Horizon Dive",
    location: "Raja Ampat, Indonesia",
    rating: 4.9,
    reviewCount: 214,
    certifications: ["PADI", "SSI"],
    description: "Award-winning dive centre operating in the heart of the Coral Triangle since 2009.",
    image: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "2",
    name: "Reef Explorer",
    location: "Great Barrier Reef, Australia",
    rating: 4.7,
    reviewCount: 389,
    certifications: ["PADI"],
    description: "Day trips and liveaboards across the outer reef — small groups, experienced guides.",
    image: "https://images.unsplash.com/photo-1583212292454-27b36f3a7414?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "3",
    name: "Palau Diving Club",
    location: "Koror, Palau",
    rating: 4.8,
    reviewCount: 156,
    certifications: ["PADI", "NAUI"],
    description: "Specialising in blue-corner wall dives and WWII wreck exploration.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "4",
    name: "Maldives Deep",
    location: "Malé, Maldives",
    rating: 4.6,
    reviewCount: 278,
    certifications: ["SSI"],
    description: "Liveaboard specialists covering all 26 atolls of the Maldivian archipelago.",
    image: "https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "5",
    name: "Galapagos Dive Academy",
    location: "Puerto Ayora, Ecuador",
    rating: 4.9,
    reviewCount: 112,
    certifications: ["PADI", "NAUI"],
    description: "Expert-led expeditions to world-famous dive sites including Gordon Rocks.",
    image: "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "6",
    name: "Komodo Ocean Divers",
    location: "Labuan Bajo, Indonesia",
    rating: 4.7,
    reviewCount: 191,
    certifications: ["PADI", "SSI"],
    description: "Full-service dive centre with on-site pool and liveaboard departures.",
    image: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=800&q=80",
  },
];

export const INSTRUCTORS = [
  {
    id: "1",
    name: "Marco Rossi",
    location: "Raja Ampat, Indonesia",
    certifications: ["PADI IDC Staff Instructor", "Rescue Diver"],
    divesLed: 1247,
    rating: 4.9,
    bio: "15 years diving the Coral Triangle. Specialises in underwater photography and manta encounters.",
    color: "bg-blue-400",
  },
  {
    id: "2",
    name: "Sarah Chen",
    location: "Maldives",
    certifications: ["SSI Instructor Trainer", "Nitrox Specialist"],
    divesLed: 892,
    rating: 4.8,
    bio: "Former marine biologist turned dive instructor. Expert in pelagic species and night dives.",
    color: "bg-teal-400",
  },
  {
    id: "3",
    name: "David Okafor",
    location: "Red Sea, Egypt",
    certifications: ["PADI Master Instructor", "Wreck Specialist"],
    divesLed: 2103,
    rating: 5.0,
    bio: "Wreck diving expert with over 20 years on the Red Sea. Has dived every major WWII wreck in the region.",
    color: "bg-slate-500",
  },
  {
    id: "4",
    name: "Yuki Tanaka",
    location: "Okinawa, Japan",
    certifications: ["NAUI Instructor", "Divemaster"],
    divesLed: 643,
    rating: 4.7,
    bio: "Passionate about reef conservation. Leads regular clean-up dives alongside regular dive programmes.",
    color: "bg-emerald-400",
  },
  {
    id: "5",
    name: "Elena Vasquez",
    location: "Galápagos, Ecuador",
    certifications: ["PADI IDC Staff Instructor", "Shark Research Diver"],
    divesLed: 1589,
    rating: 4.9,
    bio: "Works with the Charles Darwin Research Station. Specialises in hammerhead and whale shark encounters.",
    color: "bg-cyan-500",
  },
  {
    id: "6",
    name: "Tom Blackwell",
    location: "Palau, Micronesia",
    certifications: ["SSI Instructor", "Technical Diver"],
    divesLed: 756,
    rating: 4.8,
    bio: "Technical diving expert who pioneered several deep blue-corner dive routes.",
    color: "bg-sky-500",
  },
];

export const COURSES = [
  { id: "1", name: "Open Water Diver", level: "Beginner", days: 4, price: 450, description: "Your first step into the underwater world." },
  { id: "2", name: "Advanced Open Water", level: "Intermediate", days: 3, price: 380, description: "Deepen your skills with 5 adventure dives." },
  { id: "3", name: "Rescue Diver", level: "Advanced", days: 4, price: 520, description: "Learn to prevent and manage dive emergencies." },
  { id: "4", name: "Divemaster", level: "Professional", days: 30, price: 1200, description: "Your first professional-level certification." },
  { id: "5", name: "Nitrox Specialty", level: "Specialty", days: 2, price: 220, description: "Dive longer with enriched-air nitrox." },
];

export const FUN_DIVES = [
  { id: "1", name: "Blue Corner Wall", depth: "15–40m", duration: "2 dives", price: 120, minCert: "Advanced Open Water" },
  { id: "2", name: "Manta Ray Point", depth: "8–25m", duration: "2 dives", price: 110, minCert: "Open Water" },
  { id: "3", name: "WWII Wreck Dive", depth: "18–35m", duration: "1 dive", price: 95, minCert: "Advanced Open Water" },
  { id: "4", name: "Night Reef Dive", depth: "5–18m", duration: "1 dive", price: 85, minCert: "Open Water" },
  { id: "5", name: "Shark Drift Dive", depth: "20–40m", duration: "2 dives", price: 130, minCert: "Advanced Open Water" },
];
